spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-green-fire-aselsjx3-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require&currentSchema=hospital}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=hospital

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=hospital
spring.flyway.default-schema=hospital
spring.flyway.create-schemas=true
spring.flyway.validate-on-migrate=true
logging.level.org.flywaydb=DEBUG

# JWT configuration
app.jwt.secret=${JWT_SECRET:T2V4YW1wbGUtY2hhbmdlbWUtaW4tYS1zZWNyZXQta2V5LWF0LWxlYXN0LTMyLWNoYXJz}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
